### ISSUE TITLE
How add MQTT in time series tutorial?

### ISSUE THREAD

**Issue by sfl0r3nz05** [Fiware/tutorials.Time-Series-Data#51]
Based on the IoT-over-MQTT tutorial, I have enabled MQTT instead of HTTP for the communication between sensor and agent. So far I have not been able to find the error in my configuration?

This is the configuration for the IoT Agent:
```
  # IoT-Agent JSON
  iot-agent:
    image: fiware/iotagent-ul:${ULTRALIGHT_VERSION}
    hostname: iot-agent
    container_name: fiware-iot-agent
    restart: always
    depends_on:
      - mongo-db
      - mosquitto
    networks:
      - default
    expose:
      - "${IOTA_NORTH_PORT}"
    ports:
      - "${IOTA_NORTH_PORT}:${IOTA_NORTH_PORT}" # localhost:4041
    environment:
      - IOTA_CB_HOST=orion # name of the context broker to update context
      - IOTA_CB_PORT=${ORION_PORT} # port the context broker listens on to update context
      - IOTA_NORTH_PORT=${IOTA_NORTH_PORT}
      - IOTA_REGISTRY_TYPE=mongodb #Whether to hold IoT device info in memory or in a database
      - IOTA_LOG_LEVEL=DEBUG # The log level of the IoT Agent
      - IOTA_TIMESTAMP=true # Supply timestamp information with each measurement
      - IOTA_CB_NGSI_VERSION=v2 # use NGSIv2 when sending updates for active attributes
      - IOTA_AUTOCAST=true # Ensure Ultralight number values are read as numbers not strings
      - IOTA_MONGO_HOST=mongo-db # The host name of MongoDB
      - IOTA_MONGO_PORT=${MONGO_DB_PORT} # The port mongoDB is listening on
      - IOTA_MONGO_DB=iotagentul # The name of the database used in mongoDB
      - IOTA_MQTT_HOST=mosquitto # The host name of the MQTT Broker
      - IOTA_MQTT_PORT=1883 # The port the MQTT Broker is listening on to receive topics
      - IOTA_DEFAULT_RESOURCE= # Default is blank. I'm using MQTT so I don't need a resource
      - IOTA_PROVIDER_URL=http://iot-agent:${IOTA_NORTH_PORT}
      - IOTA_DEFAULT_TRANSPORT=MQTT
    healthcheck:
      interval: 5s
```
This is the configuration for the IoT Sensor:
```
# Tutorial acts as a series of dummy IoT Sensors over HTTP
  iot-sensors:
    image: fiware/tutorials.context-provider
    hostname: iot-sensors
    container_name: iot-sensors
    restart: always
    depends_on:
      - orion
      - quantumleap
    expose:
      - "${TUTORIAL_APP_PORT}"
      - "${TUTORIAL_DUMMY_DEVICE_PORT}"
    ports:
      - "${TUTORIAL_APP_PORT}:${TUTORIAL_APP_PORT}" # localhost:3000
      - "${TUTORIAL_DUMMY_DEVICE_PORT}:${TUTORIAL_DUMMY_DEVICE_PORT}" # localhost:3001
    environment:
      - "MONGO_URL=mongodb://mongo-db:27017"
      - "DEBUG=iot-sensors:*"
      - "WEB_APP_PORT=${TUTORIAL_APP_PORT}" # Port used by the content provider proxy and web-app for viewing data
      - "IOTA_HTTP_HOST=iot-agent"
      - "IOTA_HTTP_PORT=${IOTA_SOUTH_PORT}"
      - "IOTA_DEFAULT_RESOURCE=/iot/d"
      - "MQTT_TOPIC_PROTOCOL=ul"
      - "DUMMY_DEVICES_PORT=${TUTORIAL_DUMMY_DEVICE_PORT}" # Port used by the dummy IOT devices to receive commands
      - "DUMMY_DEVICES_TRANSPORT=MQTT" # Default transport used by dummy IoT devices
      - "CONTEXT_BROKER=http://orion:${ORION_PORT}/v2" # URL of the context broker to update context
      - "NGSI_LD_PREFIX="
      - "CRATE_DB_SERVICE_URL=http://crate-db:4200/_sql"
      - "DUMMY_DEVICES_API_KEY=4jggokgpepnvsb2uv4s40d59ov"
      - "MQTT_BROKER_URL=mqtt://mosquitto"
    networks:
      - default
```
This is the configuration for the MQTT Broker:
```
  # MQTT broker
  mosquitto:
    image: eclipse-mosquitto:1.6.14
    hostname: mosquitto
    container_name: mosquitto
    restart: always
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - default
```

Following the time series tutorial recommendation I have tried to unlock the door:

![mqtt_sensor](https://user-images.githubusercontent.com/6643905/184243997-22cf330f-e87c-43ab-b2d6-348b0fe99612.PNG)

... and this is the log obtained in the IoT Sensor with MQTT:

![mqtt_door](https://user-images.githubusercontent.com/6643905/184244141-57898e9f-9f70-4657-ab68-743c04852bd8.PNG)

... this is the log obtained for the IoT Sensor without MQTT:

![http_door](https://user-images.githubusercontent.com/6643905/184244346-fa864cd8-45f6-42d4-838a-9229e1db8d3c.PNG)

... this is the log obtained in the IoT Agent with MQTT:

![mqtt_agent](https://user-images.githubusercontent.com/6643905/184244768-0ad5a0fb-05e6-42dc-82a2-62261694f5e8.PNG)

... this is the log obtained in the Orion with MQTT:

![mqtt_orion](https://user-images.githubusercontent.com/6643905/184244682-d1dcfa23-821e-4dfb-837c-f2ff01e7a181.PNG)
